

#!/usr/bin/env python

from ROOT import *
from array import array

# ROOT general options
gROOT.SetBatch(kTRUE)
gROOT.SetStyle("Plain")
gStyle.SetOptStat("emruo")

file = TFile("METExamplesPAT_output.root")

h_GenMET  = file.Get("metExamplesPAT/h_GenMET_PAT")
h_CaloMET = file.Get("metExamplesPAT/h_CaloMET_PAT")
h_CaloMETuncorr = file.Get("metExamplesPAT/h_CaloMETuncorr_PAT")
h_TCMET   = file.Get("metExamplesPAT/h_TCMET_PAT")
h_PFMET   = file.Get("metExamplesPAT/h_PFMET_PAT")

h_GenMET.SetTitleOffset(1.25,"Y")
h_GenMET.SetLineWidth(3)
h_GenMET.SetLineColor(kBlack)
statsGenMET = TPaveStats(0.2,0.8,0.4,1.0,"brNDC")
statsGenMET.SetName("stats")
statsGenMET.SetBorderSize(1)
statsGenMET.SetTextAlign(12)
statsGenMET.SetFillColor(0)
statsGenMET.SetLineColor(kBlack)
statsGenMET.SetTextColor(kBlack)
h_GenMET.GetListOfFunctions().Add(statsGenMET)
h_CaloMET.SetLineWidth(3)
h_CaloMET.SetLineColor(kRed)
statsCaloMET = TPaveStats(0.4,0.8,0.6,1.0,"brNDC")
statsCaloMET.SetName("stats")
statsCaloMET.SetBorderSize(1)
statsCaloMET.SetTextAlign(12)
statsCaloMET.SetFillColor(0)
statsCaloMET.SetLineColor(kRed)
statsCaloMET.SetTextColor(kRed)
h_CaloMET.GetListOfFunctions().Add(statsCaloMET)
h_CaloMETuncorr.SetLineWidth(3)
h_CaloMETuncorr.SetLineColor(kMagenta)
statsCaloMETuncorr = TPaveStats(0.4,0.6,0.6,0.8,"brNDC")
statsCaloMETuncorr.SetName("stats")
statsCaloMETuncorr.SetBorderSize(1)
statsCaloMETuncorr.SetTextAlign(12)
statsCaloMETuncorr.SetFillColor(0)
statsCaloMETuncorr.SetLineColor(kMagenta)
statsCaloMETuncorr.SetTextColor(kMagenta)
h_CaloMETuncorr.GetListOfFunctions().Add(statsCaloMETuncorr)
h_TCMET.SetLineWidth(3)
h_TCMET.SetLineColor(kBlue)
statsTCMET = TPaveStats(0.6,0.8,0.8,1.0,"brNDC")
statsTCMET.SetName("stats")
statsTCMET.SetBorderSize(1)
statsTCMET.SetTextAlign(12)
statsTCMET.SetFillColor(0)
statsTCMET.SetLineColor(kBlue)
statsTCMET.SetTextColor(kBlue)
h_TCMET.GetListOfFunctions().Add(statsTCMET)
h_PFMET.SetLineWidth(3)
h_PFMET.SetLineColor(kGreen+2)
statsPFMET = TPaveStats(0.8,0.8,1.0,1.0,"brNDC")
statsPFMET.SetName("stats")
statsPFMET.SetBorderSize(1)
statsPFMET.SetTextAlign(12)
statsPFMET.SetFillColor(0)
statsPFMET.SetLineColor(kGreen+2)
statsPFMET.SetTextColor(kGreen+2)
h_PFMET.GetListOfFunctions().Add(statsPFMET)

canvas = TCanvas("c","",800,800)

h_GenMET.Draw()
h_CaloMET.Draw("sames")
h_CaloMETuncorr.Draw("sames")
h_TCMET.Draw("sames")
h_PFMET.Draw("sames")

legend = TLegend(0.7,0.55,1.0,0.8)
legend.SetBorderSize(1)
legend.SetFillColor(0)
legend.AddEntry(h_GenMET,"GenMET_PAT","l")
legend.AddEntry(h_CaloMET,"CaloMET_PAT","l")
legend.AddEntry(h_CaloMETuncorr,"CaloMETuncorr_PAT","l")
legend.AddEntry(h_TCMET,"TCMET_PAT","l")
legend.AddEntry(h_PFMET,"PFMET_PAT","l")
legend.Draw()

canvas.SaveAs("MET_PAT.png")
canvas.SetLogy()
canvas.SaveAs("MET_PAT_log.png")
